/** @file
  Host-based stub for PeimEntryPoint library class.

  AUDIT: 2026-02-15
  STATUS: FIXED — removed ASSERT(FALSE), added missing EfiMain stub.

  This library satisfies the PeimEntryPoint library class for host-based
  rehosting and fuzzing. In the real UEFI boot flow, _ModuleEntryPoint is
  the PE/COFF entry point that calls autogenerated ProcessLibraryConstructorList()
  and ProcessModuleEntryPointList(). In host mode, the fuzz harness bypasses
  this entirely and invokes target code directly.

  Functions implemented (2 of 2 declared in PeimEntryPoint.h):
    _ModuleEntryPoint  — Stub, returns EFI_SUCCESS (never called during fuzzing)
    EfiMain            — EBC compatibility wrapper, delegates to _ModuleEntryPoint

  Functions NOT implemented (autogenerated by build tools, not part of this lib):
    ProcessLibraryConstructorList   — Generated per-module by AutoGen.c
    ProcessModuleEntryPointList     — Generated per-module by AutoGen.c

  Key fixes applied:
    - Removed ASSERT(FALSE) from _ModuleEntryPoint. The old code would crash
      any fuzzer that happened to reach this path. Now returns EFI_SUCCESS
      silently, which is safe for fuzzing.
    - Added EfiMain() stub to match the PeimEntryPoint.h declaration. The
      real edk2 PeimEntryPoint.c implements this as a simple wrapper.

Copyright (c) 2006 - 2008, Intel Corporation. All rights reserved.<BR>
SPDX-License-Identifier: BSD-2-Clause-Patent

**/

#include <PiPei.h>

#include <Library/PeimEntryPoint.h>
#include <Library/DebugLib.h>

/**
  Host-stub entry point for a PEIM.

  In real UEFI, this calls ProcessLibraryConstructorList() then
  ProcessModuleEntryPointList() and returns the result. In host mode,
  this is never called — the harness invokes target code directly.

  AUDIT: Removed ASSERT(FALSE) that would crash fuzzers. Returns EFI_SUCCESS
  so any accidental call path succeeds gracefully instead of aborting.

  @param  FileHandle  Handle of the file being invoked.
  @param  PeiServices Describes the list of possible PEI Services.

  @retval  EFI_SUCCESS  Always succeeds in host mode.
**/
EFI_STATUS
EFIAPI
_ModuleEntryPoint (
  IN EFI_PEI_FILE_HANDLE       FileHandle,
  IN CONST EFI_PEI_SERVICES    **PeiServices
  )
{
  //
  // AUDIT: Was ASSERT(FALSE); return EFI_UNSUPPORTED — would crash fuzzers.
  // In host-based fuzzing the entry point is never the intended target;
  // the harness calls into specific protocol/library functions directly.
  // Return EFI_SUCCESS so accidental calls don't abort the process.
  //
  return EFI_SUCCESS;
}

/**
  EBC compatibility entry point for a PEIM.

  This is declared in PeimEntryPoint.h as an EBC wrapper. The real edk2
  implementation simply delegates to _ModuleEntryPoint. We do the same
  for API completeness.

  @param  FileHandle  Handle of the file being invoked.
  @param  PeiServices Describes the list of possible PEI Services.

  @retval  EFI_SUCCESS  Always succeeds in host mode.
**/
EFI_STATUS
EFIAPI
EfiMain (
  IN EFI_PEI_FILE_HANDLE       FileHandle,
  IN CONST EFI_PEI_SERVICES    **PeiServices
  )
{
  return _ModuleEntryPoint (FileHandle, PeiServices);
}

