/** @file
  Host-based stub for UefiDriverEntryPoint library class.

  AUDIT: 2026-02-15
  STATUS: FIXED — removed ASSERT(FALSE), added missing EfiMain, ExitDriver,
  and _DriverUnloadHandler stubs.

  This library satisfies the UefiDriverEntryPoint library class for host-based
  rehosting and fuzzing.  In the real UEFI boot flow, _ModuleEntryPoint is the
  PE/COFF entry point that calls autogenerated ProcessLibraryConstructorList()
  and ProcessModuleEntryPointList().  In host mode, the fuzz harness bypasses
  this entirely and invokes target code directly through RunTestHarness().

  Functions implemented (4 of 4 declared in UefiDriverEntryPoint.h):
    _ModuleEntryPoint       — Stub, returns EFI_SUCCESS (never called during fuzzing)
    EfiMain                 — EBC compatibility wrapper, delegates to _ModuleEntryPoint
    _DriverUnloadHandler    — Stub unload handler, returns EFI_SUCCESS
    ExitDriver              — Stub, no-op (would normally call gBS->Exit which is
                              not meaningful on host)

  Functions NOT implemented (autogenerated by build tools, not part of this lib):
    ProcessLibraryConstructorList   — Generated per-module by AutoGen.c
    ProcessModuleEntryPointList     — Generated per-module by AutoGen.c
    ProcessLibraryDestructorList    — Generated per-module by AutoGen.c
    ProcessModuleUnloadList         — Generated per-module by AutoGen.c

  Globals provided (required by the header, defined here for host builds):
    _gUefiDriverRevision    — Set to 0 (no revision check)
    _gDriverUnloadImageCount — Set to 0 (no unload handler registration)
    _gDxeRevision           — Set to 0 (no DXE revision check)

  Key fixes applied:
    - Removed ASSERT(FALSE) from _ModuleEntryPoint. The old code would crash
      any fuzzer that happened to reach this path. Now returns EFI_SUCCESS
      silently, which is safe for fuzzing.
    - Added EfiMain() stub to match the UefiDriverEntryPoint.h declaration.
    - Added _DriverUnloadHandler() returning EFI_SUCCESS.
    - Added ExitDriver() as a no-op.
    - Added extern globals _gUefiDriverRevision, _gDriverUnloadImageCount,
      _gDxeRevision so that any module linking this library will have them
      resolved without the autogenerated code that normally provides them.

  Suitability: Fully suitable for rehosting & fuzzing. Any edk2 DXE Driver,
  DXE Runtime Driver, DXE SMM Driver, or UEFI Driver linking UefiDriverEntryPoint
  will compile and link correctly with this host stub.

Copyright (c) 2006 - 2011, Intel Corporation. All rights reserved.<BR>
SPDX-License-Identifier: BSD-2-Clause-Patent

**/



#include <Uefi.h>

#include <Protocol/LoadedImage.h>

#include <Library/UefiDriverEntryPoint.h>
#include <Library/BaseLib.h>
#include <Library/DebugLib.h>
#include <Library/UefiBootServicesTableLib.h>

//
// AUDIT: These globals are normally provided by AutoGen.c for each module.
// In host mode we define them here so any code referencing them links correctly.
//
CONST UINT32  _gUefiDriverRevision    = 0;
CONST UINT8   _gDriverUnloadImageCount = 0;
CONST UINT32  _gDxeRevision           = 0;


/**
  Unloads an image from memory.

  This function is a callback that a driver registers to do cleanup
  when the UnloadImage boot service function is called.

  AUDIT: Stub — returns EFI_SUCCESS.  In host mode, image unloading is not
  meaningful.  The ProcessModuleUnloadList and ProcessLibraryDestructorList
  functions would be autogenerated; we skip them here.

  @param  ImageHandle The handle to the image to unload.

  @return EFI_SUCCESS  Always succeeds in host mode.

**/
EFI_STATUS
EFIAPI
_DriverUnloadHandler (
  EFI_HANDLE  ImageHandle
  )
{
  return EFI_SUCCESS;
}


/**
  The entry point of PE/COFF Image for a DXE Driver, DXE Runtime Driver, DXE SMM 
  Driver, or UEFI Driver. 

  AUDIT: Was ASSERT(FALSE); return EFI_UNSUPPORTED — would crash fuzzers.
  In host-based fuzzing the entry point is never the intended target;
  the harness calls into specific protocol/library functions directly.
  Return EFI_SUCCESS so accidental calls don't abort the process.

  @param  ImageHandle  The image handle of the DXE Driver, DXE Runtime Driver, 
                       DXE SMM Driver, or UEFI Driver.
  @param  SystemTable  A pointer to the EFI System Table.

  @retval  EFI_SUCCESS  Always succeeds in host mode.

**/
EFI_STATUS
EFIAPI
_ModuleEntryPoint (
  IN EFI_HANDLE        ImageHandle,
  IN EFI_SYSTEM_TABLE  *SystemTable
  )
{
  //
  // AUDIT: Was ASSERT(FALSE); return EFI_UNSUPPORTED — would crash fuzzers.
  // In host-based fuzzing the entry point is never the intended target;
  // the harness calls into specific protocol/library functions directly.
  // Return EFI_SUCCESS so accidental calls don't abort the process.
  //
  return EFI_SUCCESS;
}


/**
  Required by the EBC compiler and identical in functionality to _ModuleEntryPoint().

  AUDIT: Added — was missing from the host stub.  The real edk2
  DriverEntryPoint.c implements this as a simple wrapper.

  @param  ImageHandle  The image handle of the DXE Driver, DXE Runtime Driver, DXE
                       SMM Driver, or UEFI Driver.
  @param  SystemTable  A pointer to the EFI System Table.

  @retval  EFI_SUCCESS  Always succeeds in host mode.
**/
EFI_STATUS
EFIAPI
EfiMain (
  IN EFI_HANDLE        ImageHandle,
  IN EFI_SYSTEM_TABLE  *SystemTable
  )
{
  return _ModuleEntryPoint (ImageHandle, SystemTable);
}


/**
  Invokes the library destructors for all dependent libraries and terminates
  the DXE Driver.

  AUDIT: Added — was missing from the host stub.  The real edk2 implementation
  calls ProcessLibraryDestructorList() then gBS->Exit().  In host mode this is
  a no-op since process lifecycle is managed by the OS, not UEFI boot services.

  @param  Status  Status returned by the driver that is exiting.

**/
VOID
EFIAPI
ExitDriver (
  IN EFI_STATUS  Status
  )
{
  //
  // AUDIT: No-op in host mode.
  // In real firmware this would call ProcessLibraryDestructorList() and then
  // gBS->Exit(). On the host, the process exits normally when the harness
  // returns, so this stub is intentionally empty.
  //
}


