/** @file ToolChainHarnessLib.c
    HBFAplus Toolchain Harness Library - Main entry point for AFL++ fuzzing.

    This library provides the main() entry point for fuzzing harnesses.
    It handles:
    - One-time initialization via InitializeHarness()
    - Per-iteration setup (buffer, timer reset)
    - Cleanup registration via atexit()

    Architecture:
    1. main() is called by AFL++ (each forked child runs once)
    2. First call triggers InitializeHarness() and registers CleanupHarness()
    3. Each iteration: reset timer, set fuzz buffer, call RunTestHarness()
    4. On exit: CleanupHarness() is called via atexit()

    Harness Contract:
    - Harness MUST implement: InitializeHarness(), CleanupHarness(),
      RunTestHarness(), GetMaxBufferSize()
    - InitializeHarness: One-time setup (allocate persistent structures)
    - CleanupHarness: Free persistent allocations
    - RunTestHarness: Per-iteration test execution
    - GetMaxBufferSize: Return max fuzz input size

    Based on HBFA's original ToolChainHarnessLib.c with HBFAplus extensions.

    Copyright (c) 2019, Intel Corporation. All rights reserved.
    Copyright (c) 2024, HBFAplus Contributors. All rights reserved.
    SPDX-License-Identifier: BSD-2-Clause-Patent
**/

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>

#include <Uefi.h>

#include <Library/BaseLib.h>
#include <Library/BaseMemoryLib.h>
#include <Library/MemoryAllocationLib.h>
#include <Library/ToolChainHarnessLib.h>
#include <Library/FuzzContextLib.h>
#include <Library/DebugLib.h>


#ifdef TEST_WITH_INSTRUMENT
#include <Library/InstrumentHookLib.h>
#endif

//
// ============================================================================
// Library Constructor/Destructor Functions (Auto-generated in AutoGen.c)
// ============================================================================
//
// In native UEFI, the DXE dispatcher calls library constructors automatically.
// In HBFAplus (rehosted to userspace), there is NO DXE dispatcher - we must
// call ProcessLibraryConstructorList() explicitly to initialize gBS, gST,
// protocol databases, and other library state.
//
// These functions are auto-generated by EDK2 build system in AutoGen.c
// based on CONSTRUCTOR entries in library INF files.
//

/**
  Process all library constructor functions.

  Auto-generated by EDK2 build in AutoGen.c. Calls constructors like:
  - UefiBootServicesTableLibConstructor (sets up gBS, gST)
  - MockEventLibConstructor (patches event functions)
  - Other library constructors based on dependencies

  MUST be called before any UEFI library functions are used.
**/
extern VOID EFIAPI ProcessLibraryConstructorList (VOID);

/**
  Process all library destructor functions.

  Auto-generated by EDK2 build in AutoGen.c. Calls destructors for
  cleanup when the module exits.
**/
extern VOID EFIAPI ProcessLibraryDestructorList (VOID);

//
// ============================================================================
// External Functions - Implemented by each harness
// ============================================================================
//
// These functions MUST be implemented by every HBFAplus harness.
// The build will fail with undefined symbol errors if they're missing.
//

/**
  One-time harness initialization.

  Called once before the AFL forkserver starts. Use this to:
  - Allocate persistent data structures
  - Initialize mock protocols
  - Set up any state that persists across fuzz iterations

  Example:
    VOID EFIAPI InitializeHarness(VOID) {
      MockTimerInit();
      mService = AllocateZeroPool(sizeof(MY_SERVICE));
    }
**/
extern VOID EFIAPI InitializeHarness (VOID);

/**
  Cleanup harness resources.

  Called on process exit (via atexit). Use this to:
  - Free persistent allocations made in InitializeHarness
  - Clean up any global state

  Example:
    VOID EFIAPI CleanupHarness(VOID) {
      if (mService != NULL) FreePool(mService);
    }
**/
extern VOID EFIAPI CleanupHarness (VOID);

/**
  Per-iteration test execution.

  Called for each fuzz input after generic setup (timer reset, fuzz
  buffer pool initialization).  The harness receives the shared
  MOCK_FUZZ_CONTEXT — fuzz buffer, size, offset, and timer advance are
  all encapsulated within it.

  @param[in]  FuzzCtx  Shared fuzz context
**/
extern VOID EFIAPI RunTestHarness (IN MOCK_FUZZ_CONTEXT *FuzzCtx);

/**
  Get maximum fuzz buffer size.

  Returns the maximum size of fuzz input this harness can accept.
  Used to allocate the test buffer.

  @return  Maximum buffer size in bytes
**/
extern UINTN EFIAPI GetMaxBufferSize (VOID);

/**
  Return the number of bootstrap bytes to reserve for driver initialization.

  This is a weak symbol — harnesses that do not override it get the
  default (0), which means no bootstrap region is reserved and the
  entire fuzz input is available to RunTestHarness.

  When a harness returns a non-zero value, ToolChainHarnessLib sets a
  soft Limit on the fuzz pool before calling ProcessLibraryConstructorList
  and InitializeHarness, then clears the limit and advances the offset
  past the bootstrap region before RunTestHarness.  This makes the seed
  layout deterministic:

      [ bootstrap bytes | harness payload ]
       ^                 ^
       0           GetBootstrapSize()

  @return  Number of bytes to reserve, or 0 for no reservation.
**/
UINTN
EFIAPI
__attribute__((weak))
GetBootstrapSize (
  VOID
  )
{
  return 0;
}

/**
  Set the global advance context so that timer-driven events
  callbacks be driven by timer advance.  Defined in
  UefiBootServicesTableLibHost/EventHost.c.
**/
extern
VOID
EFIAPI
MockEventSetAdvanceContext (
  IN MOCK_FUZZ_CONTEXT  *Ctx
  );

/**
  Initialize the deterministic timer service.
  Registers TimerAdvanceFn on the global pool so AdvanceTime can
  advance simulated time.  Defined in EventHost.c.
**/
extern
VOID
EFIAPI
MockTimerInit (
  VOID
  );

/**
  Reset all event and timer state for a new fuzz iteration.
  Clears events, close listeners, simulated time, and firing guard.
  Defined in EventHost.c.
**/
extern
VOID
EFIAPI
MockEventResetState (
  VOID
  );

//
// ============================================================================
// Global State
// ============================================================================
//

//
// Shared fuzz context pointer — obtained once during init from
// MockFuzzContextGetPool().  Passed to RunTestHarness() each iteration and
// used as the advance context.  Lives for the lifetime of the process.
//
STATIC MOCK_FUZZ_CONTEXT  *gFuzzCtx = NULL;

//
// ============================================================================
// Cleanup Wrapper
// ============================================================================
//

/**
  Wrapper function for atexit() registration.

  atexit() requires a void(*)(void) function pointer, but EFIAPI may add
  calling convention attributes. This wrapper ensures compatibility.

  Calls CleanupHarness (harness-specific cleanup) first, then
  ProcessLibraryDestructorList (library destructors).
**/
STATIC
VOID
CleanupHarnessWrapper (
  VOID
  )
{
  DEBUG ((DEBUG_INFO, "HBFAplus: Calling CleanupHarness via atexit\n"));
  CleanupHarness ();

  //
  // Call library destructors after harness cleanup.
  // This mirrors how UEFI unloads modules - module cleanup first,
  // then library destructors in reverse order of construction.
  //
  DEBUG ((DEBUG_INFO, "HBFAplus: Calling ProcessLibraryDestructorList\n"));
  ProcessLibraryDestructorList ();
}

//
// ============================================================================
// Instrumentation Support
// ============================================================================
//

#ifdef TEST_WITH_INSTRUMENT
/**
  Read instrument profile from file.

  Used for error injection testing. Reads a profile file that specifies
  which error injection points should trigger.

  @param[in]  FileName  Path to instrument profile file
**/
VOID
ReadInstrumentProfile (
  IN CHAR8  *FileName
  )
{
  VOID  *Buffer;

  FILE *f = fopen (FileName, "rb");
  if (f == NULL) {
    fputs ("File error", stderr);
    exit (1);
  }
  fseek (f, 0, SEEK_END);

  UINTN  fsize = ftell (f);
  rewind (f);

  Buffer = malloc (fsize);
  size_t  bytes_read = fread ((void *)Buffer, 1, fsize, f);
  if ((UINTN)bytes_read != fsize) {
    fputs ("File error", stderr);
    exit (1);
  }
  fclose (f);

  InstrumentHookLibInit (Buffer, fsize);
}
#endif

//
// ============================================================================
// Test Buffer Initialization
// ============================================================================
//

/**
  Initialize test buffer from command line arguments.

  Reads fuzz input from a file specified on the command line.
  This is the standard AFL mode where AFL passes input via file.

  @param[in]   argc           Argument count
  @param[in]   argv           Argument vector (argv[1] is input file)
  @param[in]   MaxBufferSize  Maximum buffer size to allocate
  @param[out]  TestBuffer     Receives allocated buffer
  @param[out]  BufferSize     Receives actual data size

  @return  None (exits on error)
**/
VOID
InitTestBuffer (
  IN  int    argc,
  IN  char   **argv,
  IN  UINTN  MaxBufferSize,
  OUT VOID   **TestBuffer,
  OUT UINTN  *BufferSize
  )
{
  VOID  *Buffer;

  //
  // 1. Allocate buffer to hold fuzz input
  //
  Buffer = AllocatePool (MaxBufferSize);
  if (Buffer == NULL) {
    fputs ("Memory allocation failed", stderr);
    exit (1);
  }

  *TestBuffer = Buffer;
  if (BufferSize == NULL) {
    printf ("error - Null pointer for BufferSize\n");
    exit (1);
  }
  *BufferSize = MaxBufferSize;

  //
  // 2. Initialize buffer - Read fuzz input from file
  //
  if (argc < 2) {
    printf ("error - missing input file\n");
    printf ("Usage: %s <input_file>\n", argv[0]);
    exit (1);
  }

  CHAR8  *FileName = argv[1];

  FILE  *f = fopen (FileName, "rb");
  if (f == NULL) {
    fprintf (stderr, "Cannot open input file: %s\n", FileName);
    exit (1);
  }

  //
  // Get file size
  //
  fseek (f, 0, SEEK_END);
  UINTN  fsize = ftell (f);
  rewind (f);

  //
  // Cap at max buffer size
  //
  fsize = (fsize > MaxBufferSize) ? MaxBufferSize : fsize;

  //
  // Read file contents into buffer
  //
  size_t  bytes_read = fread ((void *)Buffer, 1, fsize, f);
  if ((UINTN)bytes_read != fsize) {
    fputs ("File read error", stderr);
    fclose (f);
    exit (1);
  }
  fclose (f);

  *BufferSize = fsize;

#ifdef TEST_WITH_INSTRUMENT
  //
  // Error injection mode: Read instrument profile if provided
  //
  if (argc >= 3) {
    ReadInstrumentProfile (argv[2]);
  }
#endif
}

//
// ============================================================================
// Entry Points
// ============================================================================
//

#ifdef TEST_WITH_LIBFUZZER

int
LLVMFuzzerTestOneInput (
  const uint8_t  *Data,
  size_t         Size
  )
{
  STATIC BOOLEAN  mSetupDone   = FALSE;
  STATIC VOID     *mTestBuffer = NULL;
  UINTN           MaxBufferSize;
  UINTN           BootstrapSize;

  if ((Data == NULL) || (Size == 0)) {
    return 0;
  }

  //
  // Data dies on return but atexit cleanup may still read it, so copy.
  //
  MaxBufferSize = GetMaxBufferSize ();
  if (Size > MaxBufferSize) {
    Size = MaxBufferSize;
  }

  if (mTestBuffer == NULL) {
    mTestBuffer = AllocateZeroPool (MaxBufferSize);
    if (mTestBuffer == NULL) {
      return 0;
    }
  }

  ZeroMem (mTestBuffer, MaxBufferSize);
  CopyMem (mTestBuffer, Data, Size);

  // Must precede constructors: they consume from the pool.
  gFuzzCtx = MockFuzzContextGetPool ();
  MockFuzzContextInit (gFuzzCtx, (UINT8 *)mTestBuffer, (UINTN)Size);

  BootstrapSize = GetBootstrapSize ();
  if (BootstrapSize > 0) {
    MockFuzzContextSetLimit (gFuzzCtx, BootstrapSize);
  }

  MockTimerInit ();
  MockEventResetState ();
  MockEventSetAdvanceContext (gFuzzCtx);

  //
  // Not safe to run twice per process. Under a persistent loop constructors
  // see input #1's bootstrap bytes only; AFL_FUZZER_LOOPCOUNT=1 avoids that.
  //
  if (!mSetupDone) {
    DEBUG ((DEBUG_INFO, "HBFAplus: Calling ProcessLibraryConstructorList\n"));
    ProcessLibraryConstructorList ();
    DEBUG ((DEBUG_INFO, "HBFAplus: Running InitializeHarness\n"));
    InitializeHarness ();
    atexit (CleanupHarnessWrapper);
    mSetupDone = TRUE;
  }

  if (BootstrapSize > 0) {
    MockFuzzContextClearLimit (gFuzzCtx);
    MockFuzzContextAdvanceTo (gFuzzCtx, BootstrapSize);
  }

  RunTestHarness (gFuzzCtx);
  MockFuzzContextReset (gFuzzCtx);

  return 0;
}

#else

//
// ============================================================================
// Entry Point — AFL++ mode
// ============================================================================
//

/**
  Main entry point for AFL++ fuzzing.

  AFL passes input via a file specified on the command line.
  In standard AFL mode (no __AFL_INIT / __AFL_LOOP), the fork server
  sits at the first instrumented basic block.  Every forked child
  starts fresh from here, so each process runs once and exits.

  Flow:
  1. Read fuzz input from file
  2. Initialize fuzz context pool and load bytes
  3. Call library constructors and harness init
  4. Run test
  5. Cleanup via atexit

  @param[in]  argc  Argument count
  @param[in]  argv  Argument vector (argv[1] = input file)

  @return  0 on success, non-zero on error
**/
int
main (
  int   argc,
  char  **argv
  )
{
  VOID   *TestBuffer;
  UINTN  TestBufferSize;
  UINTN  BootstrapSize;

  //
  // 1. Read fuzz input from file into buffer.
  //
  InitTestBuffer (argc, argv, GetMaxBufferSize (), &TestBuffer, &TestBufferSize);

  //
  // 2. Acquire pool and load fuzz bytes BEFORE constructors —
  //    mock constructors consume from the pool.
  //
  //    In standard AFL mode (no __AFL_INIT / __AFL_LOOP), the fork server
  //    sits at the first instrumented basic block.  Every forked child
  //    starts fresh from here, so there is no "subsequent iteration" —
  //    each process runs once and exits.
  //
  gFuzzCtx = MockFuzzContextGetPool ();
  MockFuzzContextInit (gFuzzCtx, (UINT8 *)TestBuffer, TestBufferSize);

  //
  // 3. Bootstrap region setup.
  //    If the harness declares a bootstrap size, set a soft limit so
  //    that constructors and InitializeHarness can only consume bytes
  //    within the bootstrap region.  This makes the seed layout
  //    deterministic: [ bootstrap | harness payload ].
  //
  BootstrapSize = GetBootstrapSize ();
  if (BootstrapSize > 0) {
    DEBUG ((DEBUG_INFO, "HBFAplus: Bootstrap region = %u bytes\n", (UINT32)BootstrapSize));
    MockFuzzContextSetLimit (gFuzzCtx, BootstrapSize);
  }

  //
  // 4. Pre-constructor environment setup.
  //    MockTimerInit: one-time init — marks timer active, registers
  //    TimerAdvanceFn on the pool so AdvanceTime can advance time.
  //    MockEventResetState: per-iteration reset — clears events,
  //    close listeners, simulated time, and firing guard.
  //    MockEventSetAdvanceContext: sets the advance context so that
  //    MockFuzzContextAdvanceTime can signal registered events.
  //
  MockTimerInit ();
  MockEventResetState ();
  MockEventSetAdvanceContext (gFuzzCtx);

  //
  // 5. Call library constructors.
  //    In native UEFI the DXE dispatcher does this automatically.
  //    In HBFAplus (rehosted to userspace Linux) we do it manually.
  //
  DEBUG ((DEBUG_INFO, "HBFAplus: Calling ProcessLibraryConstructorList\n"));
  ProcessLibraryConstructorList ();

  //
  // 6. Harness-specific one-time init.
  //
  DEBUG ((DEBUG_INFO, "HBFAplus: Running InitializeHarness\n"));
  InitializeHarness ();
  atexit (CleanupHarnessWrapper);

  //
  // 7. End bootstrap region.
  //    Clear the limit so RunTestHarness has access to the full remaining
  //    buffer.  Advance the offset to exactly BootstrapSize so the harness
  //    payload starts at a fixed, seed-friendly position regardless of how
  //    many bootstrap bytes were actually consumed.
  //
  if (BootstrapSize > 0) {
    DEBUG ((DEBUG_INFO, "HBFAplus: Bootstrap consumed %u / %u bytes\n",
            (UINT32)gFuzzCtx->Offset, (UINT32)BootstrapSize));
    MockFuzzContextClearLimit (gFuzzCtx);
    MockFuzzContextAdvanceTo (gFuzzCtx, BootstrapSize);
  }

  //
  // 8. Run harness, cleanup.
  //
  RunTestHarness (gFuzzCtx);
  MockFuzzContextReset (gFuzzCtx);

  //
  // Note: TestBuffer is intentionally NOT freed here.  CleanupHarness
  // (registered via atexit) may trigger driver disconnect paths that
  // issue protocol commands reading from the fuzz buffer.  Freeing
  // the buffer before atexit runs causes a use-after-free.  The OS
  // reclaims all heap memory on process exit.
  //

  return 0;
}

#endif /* TEST_WITH_LIBFUZZER */
